---
- hosts: ASA
  gather_facts: false
  #connection: local
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      authorize: yes
      auth_pass: "{{ password }}"

  tasks:
  - name: ASA show inventory
    asa_command:
      commands: 
      - show inventory
      provider: "{{ cli }}"
      wait_for: 
        #msg: Expected ASA5505 in show inventory
        #delay: 2
        - result[0] contains ASA55055
    register: asa_inv
    ignore_errors: yes
    delegate_to: localhost

#  - name: asa inventory
#    debug: var=asa_inv
  - name: asa inventory fail
    debug: 
      msg: "Expected '{{ asa_inv.failed_conditions }}' in show inventory"
    when: asa_inv|failed

  - name: ASA show route connected
    asa_command:
      commands: 
      - show route connec
      provider: "{{ cli }}"
      wait_for:
        #msg: Expected defult route
        - result[0] contains 'network 0.0.0.0' 
    register: asa_route_c
    ignore_errors: yes
    delegate_to: localhost

#  - name: asa route
#    debug: var=asa_route_c
  - name: asa route failed
    debug: 
      msg: "Expected '{{ asa_route_c.failed_conditions }}' in show route connected"
    when: asa_route_c|failed